name: opencv-wrench-demo
base: core22
version: '0.1'
summary: Demonstrate OpenCv by detecting wrenches with a camera
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable
confinement: strict

apps:
  annotation:
    command: usr/bin/opencv_annotation
    extensions: [ gnome ]
    plugs:
      - home
  version:
    command: usr/bin/opencv_version
    extensions: [ gnome ]
    plugs:
      - home
  traincascade:
    command: usr/bin/opencv_traincascade
    extensions: [ gnome ]
    plugs:
      - home
  interactive-calibration:
    command: usr/bin/opencv_interactive-calibration
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/samba:$SNAP/usr/lib/atlas-base/atlas
    extensions: [ gnome ]
    plugs:
      - camera
      - home
      - process-control
  createsamples:
    command: usr/bin/opencv_createsamples
    extensions: [ gnome ]
    plugs:
      - home
  visualisation:
    command: usr/bin/opencv_visualisation
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/samba:$SNAP/usr/lib/atlas-base/atlas
    extensions: [ gnome ]
    plugs:
      - home

parts:
  opencv:
    plugin: cmake
    source: https://github.com/opencv/opencv.git
    source-branch: 3.4
    source-depth: 1
    cmake-generator: Ninja
    cmake-parameters:
      - -DINSTALL_C_EXAMPLES=ON
      - -DINSTALL_PYTHON_EXAMPLES=ON
      - -DBUILD_EXAMPLES=ON
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DOPENCV_EXTRA_MODULES_PATH=contrib/modules
      - -DWITH_JASPER=ON
      - -DBUILD_opencv_apps=ON
    override-build: |
      git-force-clone -b 3.4 https://github.com/opencv/opencv_contrib.git contrib
      craftctl default
    build-packages:
      - libjpeg-dev
      - libtiff5-dev
      - libpng-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libv4l-dev
      - libxvidcore-dev
      - libx264-dev
      - libatlas-base-dev
      - libva-dev
      - libeigen3-dev
      - libgtk2.0-dev
      - libclc-12-dev
      - libopenjp2-7-dev
      - python3-dev
      - python3-numpy
      - libopenjpip7
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libdc1394-dev
      - libogre-1.9-dev
      - libtesseract-dev
      - libgtkglext1-dev
      - libvtk9-dev
      - liblapack-dev
      - git-extras
      - libvpx-dev
    stage-packages:
      - libaec0
      - libaom3
      - libatlas3-base
      - libavcodec58
      - libavcodec-extra58
      - libavformat58
      - libavformat-extra58
      - libavutil56
      - libbluray2
      - libchromaprint1
      - libcodec2-1.0
      - libdav1d5
      - libdc1394-25
      - libgif7
      - libgme0
      - libgsm1
      - libhdf5-103-1
      - libilmbase25
      - liblept5
      - libmfx1
      - libnorm1
      - libnuma1
      - libopenexr25
      - libopenmpt0
      - libpgm-5.3-0
      - librabbitmq4
      - libshine3
      - libsnappy1v5
      - libsodium23
      - libsoxr0
      - libsrt1.4-gnutls
      - libssh-gcrypt-4
      - libswresample3
      - libswscale5
      - libsz2
      - libtesseract4
      - libudfread0
      - libusb-1.0-0
      - libva-drm2
      - libva-wayland2
      - libva-x11-2
      - libvdpau1
      - libwebpmux3
      - libx264-163
      - libx265-199
      - libxvidcore4
      - libzmq5
      - libzvbi0
      - ocl-icd-libopencl1
      - libv4l-0
      - libv4lconvert0
      - python3-numpy
      - libvpx7

