name: opencv-wrench-demo
base: core22
version: '0.1'
summary: Demonstrate OpenCv by detecting wrenches with a camera
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable
confinement: strict

apps:
  annotation:
    command: usr/bin/opencv_annotation
    extensions: [ gnome ]
    plugs:
      - home
  version:
    command: usr/bin/opencv_version
    extensions: [ gnome ]
    plugs:
      - home

parts:
  opencv:
    plugin: cmake
    source: https://github.com/opencv/opencv.git
    source-branch: 4.x
    source-depth: 1
    cmake-parameters:
      - -DINSTALL_C_EXAMPLES=ON
      - -DINSTALL_PYTHON_EXAMPLES=ON
      - -DBUILD_EXAMPLES=ON
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DWITH_JASPER=ON
    build-packages:
      - libjpeg-dev
      - libtiff5-dev
      - libpng-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libv4l-dev
      - libxvidcore-dev
      - libx264-dev
      - libatlas-base-dev
      - libva-dev
      - libeigen3-dev
      - libgtk2.0-dev
      - libclc-12-dev
      - libopenjp2-7-dev
      - python3-dev
